### PR TITLE
fix: undo the use of globalThis

### LINKED ISSUE #13: globalThis
Because of 92b2739daa7be346e27db4eba5ddc9b8f1a985e7 (where you refactored code to use globalThis) support of node versions older than v12 where dropped (because older node versions doesn't have support of globalThis), which is a breaking change, so you should either:

- Update major version of your package instead of updating minor version (should be 2.0.0 instead of 1.2.0) and remove version 1.2.0 and 1.2.1 from npm repository
- Do not use globalThis

If you will not do that a lot of packages that has your package as dependency will fail. I faced this issue right now.
Could you please fix this. Thank you :)

### PR DESCRIPTION
**Pull request by mrzalyaul**
I undo the [last changes](https://github.com/feross/queue-microtask/commit/92b2739daa7be346e27db4eba5ddc9b8f1a985e7) you did about `globalthis`, because all the projects that use a version that doesn't support `globalThis` are down !!  ( for example, all the projects that use `react-scripts` stopped working because the `run-parallel` package has microTask as a dependency, and because of that all react apps that use node version 11 for example are down too. ).

fix: https://github.com/feross/queue-microtask/issues/13 , https://github.com/feross/queue-microtask/issues/17

### CODE REVIEW

**Comment by tm-ssingh** [comment]
can we get it working for node v11? My cordova project stopped working because of this. :(
I see closure of this open issue without any solution..

**Review by jindrahm — APPROVED** [review]

**Comment by veryaustin** [comment]
Running into the same issue with our build system in node v11 with serverless deployment. globalThis is not defined.

**Comment by maikelmclauflin** [comment]
odd that it only cropped up in the last week, but i am running into this as well

**Review by maikelmclauflin — APPROVED** [review]

**Comment by maikelmclauflin** [comment]
for now @veryaustin, @jindrahm, @mrzalyaul i was able to just fork @mrzalyaul 's install that using `npm i --save "brave-intl/queue-microtask#master"` and that seemed to fix the problem.

**Comment by jindrahm** [comment]
@maikelmclauflin thanks.. I've worked that around with a postinstall script

`const fs = require('fs');

if (!fs.existsSync('./node_modules/queue-microtask')) {
	process.exit(0);
}

const data = fs.readFileSync('./node_modules/queue-microtask/index.js', {encoding: 'utf-8'});

fs.writeFileSync(
	'./node_modules/queue-microtask/index.js',
	data.replace('globalThis', 'typeof window !== \'undefined\' ? window : global'),
	{encoding: 'utf-8'}
);`

**Comment by feross** [comment]
Hi everyone, a new version that removes `globalThis` has been released as `1.2.3`.

**Pull request closed without merging**
